pull_request_rules:
  - name: Automatic merge on approval if project/plugins.sbt was changed
    conditions:
      - "check-success=build"
      - files=project/plugins.sbt
      - "#files=1"
    actions:
      merge:
        method: merge
  - name: Automatic merge on approval if project/Dependencies.scala was changed
    conditions:
      - "check-success=build"
      - files=project/Dependencies.scala
      - "#files=1"
    actions:
      merge:
        method: merge
